### ISSUE TITLE
CPU usage of bird spikes to 100% and stays there for a while

### ISSUE THREAD

**Issue by dbfancier** [projectcalico/calico-bird#102] opened 2022-05-11 02:53 UTC
CPU usage of bird spikes to 100% and stays there for a while

## Expected Behavior

Normally, we expect the Bird's CPU usage to be between 1% and 3%,  otherwise it would take up training resources

## Current Behavior

CPU usage of bird is usually around 30%, but occasionally spikes to 100% and stays there for a while.

We did a CPU hot spot analysis using perf and found that the CPU time was concentrated in the function if_find_by_name(about 84%) and if_find_by_index(about 12%).

so I send SIGUSR1 to bird for a dump. It shows that iface_list has 30000 ~ 40000 nodes. The index field of most nodes is 0 and flags include LINK-DOWN and SHUTDOWN, and MTU is 0 (The devices on which this happens all have the same prefix "cali", generate by cni-plugin).

These devices no longer exist on the host, but remain in iface_list. Our scenario is offline training, so many pods are created and deleted every day.

Now I rebuild the list using the extreme method of "kill bird"

I wonder if kif_scan() has a problem with the interface_list maintenance mechanism. We hope the community will help identify and fix the problem.

Thanks a lot.

## Possible Solution

kill -SIGKILL "pidof bird"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
![image](https://user-images.githubusercontent.com/26991090/167759141-b5ed06f8-5081-4b8d-86bd-9315c0c68da9.png)

## Your Environment

* bird version: BIRD version v0.3.3+birdv1.6.8
* Operating System and version: CentOS Linux release 7.3.1611 (Core) 5.4.167.el7.elrepo.x86_64
* Link to your project (optional):

**Comment by splitice** [comment] 2022-06-14 04:48
Probably fixes #95

**Comment by caseydavenport** [comment] 2022-06-14 23:57
This PR seems relevant, which aims to remove interfaces from BIRD when they go away: https://github.com/projectcalico/bird/pull/103

**Comment by caseydavenport** [comment] 2022-10-04 15:14
This PR was merged to master recently: https://github.com/projectcalico/bird/pull/104

It looks like it has potential to fix this issue. We'll soak it and release it in v3.25 and hopefully we can close this then.

**Comment by caseydavenport** [comment] 2022-10-04 15:15
Actually going to close this now as a duplicate of https://github.com/projectcalico/bird/issues/95

**Closed as completed by caseydavenport** 2022-10-04 15:15 UTC

**Comment by nueavv** [comment] 2024-09-25 06:17
I sent a kill -SIGUSR1 signal to the BIRD process but can't find where the logs are being written. Could anyone share where I should be looking, especially in a container environment? It seems like I'm facing a similar issue as others might have experienced.
